# Generated by Django 3.2.15 on 2024-05-22 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspecscanresultsdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspec_result_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspecscanresultsdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='inspecscanresultsdb',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='inspecscanresultsdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspec_result_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspecscandb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspec_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspecscandb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='inspecscandb',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='inspecscandb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspec_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docklescanresultsdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dockle_result_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docklescanresultsdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='docklescanresultsdb',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='docklescanresultsdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dockle_result_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docklescandb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dockle_db_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docklescandb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='docklescandb',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='docklescandb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dockle_db_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
