# Generated by Django 3.2.15 on 2024-05-22 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('user_management', '0001_initial'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscandb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scan_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectscandb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='projectscandb',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='projectscandb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scan_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_db_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_group', to='groups.groupdb'),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='projectdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_db_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthdb',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthdb',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_management.organization'),
        ),
        migrations.AddField(
            model_name='monthdb',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectdb'),
        ),
        migrations.AddField(
            model_name='monthdb',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
