# Generated by Django 3.2.15 on 2024-05-22 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAPIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Organization API Keys',
                'db_table': 'org_apikey',
            },
        ),
    ]
