# Generated by Django 3.2.15 on 2024-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScanDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('rescan_id', models.TextField(blank=True, null=True)),
                ('scan_date', models.TextField(blank=True)),
                ('scan_status', models.TextField(blank=True)),
                ('total_vul', models.IntegerField(blank=True, null=True)),
                ('critical_vul', models.IntegerField(blank=True, null=True)),
                ('high_vul', models.IntegerField(blank=True, null=True)),
                ('medium_vul', models.IntegerField(blank=True, null=True)),
                ('low_vul', models.IntegerField(blank=True, null=True)),
                ('info_vul', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('rescan', models.TextField(blank=True, null=True)),
                ('total_dup', models.TextField(blank=True, null=True)),
                ('scanner', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Network Scans List',
                'db_table': 'networkscandb',
            },
        ),
        migrations.CreateModel(
            name='NetworkScanResultsDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.UUIDField(blank=True)),
                ('vuln_id', models.UUIDField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('severity_color', models.CharField(max_length=256, null=True)),
                ('severity', models.CharField(max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('port', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('scanner', models.TextField()),
                ('jira_ticket', models.TextField(blank=True, null=True)),
                ('dup_hash', models.TextField(blank=True, null=True)),
                ('vuln_duplicate', models.TextField(blank=True, null=True)),
                ('vuln_status', models.TextField(blank=True, null=True)),
                ('false_positive_hash', models.TextField(blank=True, null=True)),
                ('false_positive', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Network Scans Data',
                'db_table': 'networkscanresultsdb',
            },
        ),
        migrations.CreateModel(
            name='TaskScheduleDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField(blank=True, null=True)),
                ('target', models.TextField(blank=True, null=True)),
                ('schedule_time', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('project_id', models.TextField(blank=True, null=True)),
                ('scanner', models.TextField(blank=True, null=True)),
                ('periodic_task', models.TextField(blank=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Task Schedule Data',
                'db_table': 'taskscheduledb',
            },
        ),
    ]
