# Generated by Django 3.2.15 on 2024-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jirasetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('jira_server', models.TextField(blank=True, null=True)),
                ('jira_username', models.TextField(blank=True, null=True)),
                ('jira_password', models.TextField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
