# Generated by Django 3.2.15 on 2024-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logintime', models.DateTimeField(auto_now=True)),
                ('logouttime', models.DateTimeField(null=True)),
                ('IP', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'User Login Histories',
                'db_table': 'user_login_history',
            },
        ),
    ]
