# Generated by Django 3.2.15 on 2024-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('recipient_list', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GitlabDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('gitlab_url', models.TextField(default='https://gitlab.com/api/v4/projects')),
                ('gitlab_api', models.TextField(default='')),
                ('gitlab_username', models.TextField(default='')),
                ('gitlab_repo', models.TextField(default='')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NmapVulnersSettingDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('enabled', models.BooleanField()),
                ('version', models.BooleanField()),
                ('online', models.BooleanField()),
                ('timing', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('setting_name', models.TextField(blank=True, null=True)),
                ('setting_scanner', models.TextField(blank=True, null=True)),
                ('setting_status', models.BooleanField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZapSettingsDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.UUIDField(blank=True, null=True)),
                ('zap_url', models.TextField(default='127.0.0.1')),
                ('zap_api', models.TextField(default='dwed23wdwedwwefw4rwrfw')),
                ('zap_port', models.IntegerField(default=8090)),
                ('enabled', models.BooleanField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
